name: Rust - Run Clippy
description: "Run clippy for crate"

runs:
    using: "composite"
    steps:
        - uses: komrad-company/workflows/actions/rust/setup-toolchain@main

        - uses: actions/download-artifact@v4
          with:
            name: build

        - run: cargo clippy -- -D warnings
          shell: bash


