name: Rust prepare env

on:
    workflow_call:
        inputs:
            toolchain_components:
                description: Rust toolchain components to use
                type: string
                default: 'rustfmt'

jobs:
    build:
        name: Prepare env
        runs-on: ubuntu-latest
        steps:
            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                components: ${{ inputs.toolchain_components }}